apiVersion: v1
kind: LimitRange
metadata:
  name: k8s-assistant-limit-range
  namespace: kubernetes-assistant-staging
spec:
  limits:
    - type: Container
      # The maximum allowed allocation for any container
      max:
        cpu: "1"
        memory: "512Mi"
      # The absolute minimum allowed allocation for any container
      min:
        cpu: "200m"
        memory: "256Mi"
