apiVersion: v1
kind: ResourceQuota
metadata:
  name: k8s-assistant-quota
  namespace: kubernetes-assistant-staging
spec:
  hard:
    requests.cpu: "200m"
    limits.cpu: "1"
    requests.memory: "256Mi"
    limits.memory: "512Mi"
    pods: "1"
