apiVersion: v1
kind: Service
metadata:
  name: k8s-assistant-service
  namespace: kubernetes-assistant
  labels:
    app: k8s-assistant
spec:
  type: ClusterIP
  selector:
    app: k8s-assistant
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000